name: cached_network_image
description: Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
version: 2.0.0-rc.1
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cached_network_image

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">= 1.10.15-pre.148 < 2.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager:
    git:
      url: https://github.com/marcglasberg/flutter_cache_manager.git
      ref: 23cf284117f8bd362ea63d37ea694bd93547d418

dev_dependencies:
  test: ^1.3.0
